Update LiteCommands to 2.7.0, reformat code
EternalCodeTeam/EternalReports pull request #3
Opened 2022-12-05 16:48 UTC by Jakubk15

2022-12-05 21:58 UTC, Osnixer requested changes

2022-12-05 21:58 UTC, Osnixer commented on build.gradle.kts
> +    main = "com.eternalcode.eternalreports.EternalReports"
com.eternalcode prezentuje już eternal więc -> `eternalreports -> reports`

2022-12-05 22:27 UTC, vLuckyyy commented on build.gradle.kts
> +    main = "com.eternalcode.eternalreports.EternalReports"
???, Jest dobrze

com.eternalcode.**nazwa projektu**.KLASA GŁÓWNA

2022-12-06 18:57 UTC, vLuckyyy requested changes

2022-12-06 18:57 UTC, vLuckyyy commented on .github/workflows/gradle.yml
> +                run: './gradlew eternalreports:shadowJar'
```suggestion
                run: './gradlew shadowJar'
```

2022-12-06 18:57 UTC, vLuckyyy commented on .github/workflows/gradle.yml
> +                    - 17
```suggestion
                    - 8
```

2022-12-06 18:57 UTC, vLuckyyy commented on CONTRIBUTING.md
> +`[GH-{NUMBER}] Title of PR`
```suggestion
`GH-{NUMBER} Title of PR`
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +        final long millis = started.elapsed(TimeUnit.MILLISECONDS);
```suggestion
        long millis = started.elapsed(TimeUnit.MILLISECONDS);
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +            .register();
Scaliłbym to aby tak tego nie rozszeżać do body. 

Like 
```java
            .commandInstance(new ReloadConfiguration(this.configurationManager, this.notificationManager))
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +        this.liteCommands.getPlatform().unregisterAll();
Możesz również dodać takiego samego checka na nulla co w audiences.

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +    public static EternalReports eternalReports;
Wrzuć to na samą górę, oraz nazwij "instance"

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +        final Metrics metrics = new Metrics(this, 16483);
```suggestion
        Metrics metrics = new Metrics(this, 16483);
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/ReportCommand.java
> +@Route(name = "report", aliases = {"zglos"})
```suggestion
@Route(name = "report", aliases = { "zglos" })
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/ReportCommand.java
> +            });
Dodaj "Server" do konstruktora i 👇

```suggestion
        this.server.getOnlinePlayers()
            .stream()
            .filter(player -> player.hasPermission("eternalcode.report.recieve"))
            .forEach(player -> {
                this.notificationManager.announceMessage(
                    player.getUniqueId(),
                    this.messages.userMessages.reportForAdministrator
                        .replace("{USER}", target.getName())
                        .replace("{REASON}", message)
                        .replace("{REPORTED_BY}", sender.getName())
                );
            });
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/administrator/ReloadConfiguration.java
> +@Route(name = "er-reload", aliases = {"eternalreports-reload"})
```suggestion
@Route(name = "er-reload", aliases = { "eternalreports-reload" })
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/administrator/ReloadConfiguration.java
> +    private NotificationManager notificationManager;
```suggestion
public class ReloadConfiguration {

    private ConfigurationManager configurationManager;
    private ConfigService messagesManager;
    private NotificationManager notificationManager;
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/administrator/ReloadConfiguration.java
> +    @Execute()
```suggestion
    @Execute
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/EternalReports.java
> +        File dataDirectory = new File(this.getDataFolder() + "/data");
Proszę przerobić te configi na standardowy system configów np. z **EternalCore** 😎

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/ReportCommand.java
> +            });
```suggestion
        this.server.getOnlinePlayers()
            .stream()
            .filter(player -> player.hasPermission("eternalcode.report.recieve"))
            .forEach(player -> {
                this.notificationManager.announceMessage(
                    player.getUniqueId(),
                    this.messages.userMessages.reportForAdministrator
                        .replace("{USER}", target.getName())
                        .replace("{REASON}", message)
                        .replace("{REPORTED_BY}", sender.getName())
                );
            });
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/handlers/InvalidUsageHandler.java
> +    dev.rollczi.litecommands.handle.InvalidUsageHandler<CommandSender> {
```suggestion
public class InvalidUsage implements InvalidUsage<CommandSender> {
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/command/handlers/InvalidUsageHandler.java
> +        }
Co tu robi tak statycznie wrzucona wiadomość?

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/message/GlobalMessages.java
> +    }
```suggestion
    public Resource resource(File folder) {
        return Source.of(folder, "messages.yml");
    }
```

2022-12-06 18:57 UTC, vLuckyyy commented on src/main/java/com/eternalcode/reports/util/ChatUtil.java
> +}
Do usunięcia

2022-12-06 20:20 UTC, vLuckyyy approved these changes
Można się przyczepić do paru rzeczy, ale moim zdaniem to są na tyle małe rzeczy że PR zasługuje na Approve 😀!

2022-12-07 17:30 UTC, Osnixer approved these changes

2022-12-07 17:31 UTC, merged